import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { logoFromSettings } from "../config/branding";
import { defaultReportOptions, formatDate, formatDateTime, includesReport, money, reportDateRangeLabel, reportFilename, selectedReportTypes, tableTotal } from "./ReportService";

const brandGreen = [15, 122, 59];
const lightGreen = [236, 253, 245];
const borderGreen = [190, 220, 202];

function number(value) {
  return Number(value || 0).toLocaleString();
}

function paymentLabel(method) {
  if (method === "cash") return "Cash";
  if (method === "gcash") return "GCash";
  if (method === "qrph") return "GCash / QR Ph";
  if (method === "debit") return "Debit Card";
  if (method === "credit") return "Credit Card";
  if (method === "maya") return "Maya";
  if (method === "cod") return "COD";
  return method || "";
}

function statusLabel(status) {
  return String(status || "")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

async function captureElement(element) {
  if (!element) return null;
  const canvas = await html2canvas(element, { backgroundColor: "#ffffff", scale: 2, useCORS: true });
  return canvas.toDataURL("image/png");
}

function pageMetrics(doc) {
  return {
    width: doc.internal.pageSize.getWidth(),
    height: doc.internal.pageSize.getHeight(),
    margin: 14
  };
}

function addHeader(doc, report, options) {
  const { width } = pageMetrics(doc);
  doc.setFillColor(...brandGreen);
  doc.rect(0, 0, width, 30, "F");
  try {
    doc.addImage(logoFromSettings(report), "PNG", 14, 7, 14, 14);
  } catch {
    doc.setFillColor(255, 255, 255);
    doc.circle(21, 14, 7, "F");
    doc.setTextColor(...brandGreen);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.text("R", 19, 16);
  }
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("RETELA", 34, 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Tela To Pera Thrift Shop", 34, 19);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Analytics Report", width - 14, 12, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(reportDateRangeLabel(options), width - 14, 19, { align: "right" });
}

function addReportMeta(doc, report, options) {
  autoTable(doc, {
    startY: 38,
    theme: "plain",
    styles: { fontSize: 9, cellPadding: 1.5, textColor: [17, 24, 39] },
    body: [
      ["Generated", formatDateTime(new Date())],
      ["Report Date", formatDate(report.reportDate)],
      ["Prepared by", report.adminName || "Admin"],
      ["Date Range", reportDateRangeLabel(options)],
      ["Selected Reports", selectedReportTypes(options).map((item) => item.label).join(", ")]
    ],
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 32 },
      1: { cellWidth: "auto" }
    }
  });
  return doc.lastAutoTable.finalY + 8;
}

function addFooter(doc) {
  const pages = doc.internal.getNumberOfPages();
  const { width, height } = pageMetrics(doc);
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(...borderGreen);
    doc.line(14, height - 14, width - 14, height - 14);
    doc.setTextColor(80, 80, 80);
    doc.setFontSize(8);
    doc.text("Generated by RETELA System", 14, height - 8);
    doc.text(`Page ${page} of ${pages}`, width - 14, height - 8, { align: "right" });
  }
}

function ensureSpace(doc, y, required = 38) {
  const { height } = pageMetrics(doc);
  if (y + required <= height - 18) return y;
  doc.addPage();
  return 18;
}

function sectionTitle(doc, title, y) {
  const nextY = ensureSpace(doc, y, 24);
  doc.setTextColor(...brandGreen);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(title, 14, nextY);
  doc.setFont("helvetica", "normal");
  return nextY + 4;
}

function table(doc, y, head, body, options = {}) {
  autoTable(doc, {
    startY: y,
    head: [head],
    body: body.length ? body : [[options.emptyText || "No records available."]],
    theme: "grid",
    styles: { fontSize: options.fontSize || 8, cellPadding: 2.2, textColor: [17, 24, 39], lineColor: borderGreen, lineWidth: 0.15 },
    headStyles: { fillColor: brandGreen, textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [249, 252, 250] },
    columnStyles: options.columnStyles || {},
    didParseCell(data) {
      if (!body.length && data.section === "body") data.cell.colSpan = head.length;
    }
  });
  return doc.lastAutoTable.finalY + 8;
}

function addSalesSummary(doc, report, y) {
  y = sectionTitle(doc, "Sales Summary", y);
  return table(doc, y, ["Metric", "Value"], [
    ["Total Sales", money(report.summary?.total_sales)],
    ["Total Orders", number(report.summary?.total_orders)],
    ["Reportable Orders", number(report.summary?.sales_order_count)],
    ["Average Order Value", money(report.summary?.average_order_value)],
    ["Items Sold", number(report.summary?.items_sold)]
  ]);
}

function addOrdersSummary(doc, report, y) {
  y = sectionTitle(doc, "Orders Summary", y);
  const orders = report.orders || [];
  const body = orders.map((order) => [
    `#${order.id}`,
    formatDate(order.created_at),
    order.customer_name,
    number(order.quantity),
    paymentLabel(order.payment_method),
    statusLabel(order.status),
    money(order.total_amount)
  ]);
  if (orders.length) body.push(["", "", "Totals", number(tableTotal(orders, "quantity")), "", "", money(tableTotal(orders, "total_amount"))]);
  return table(doc, y, ["Order", "Date", "Customer", "Qty", "Payment", "Status", "Total"], body, { emptyText: "No orders found for this date range.", fontSize: 7.2 });
}

function addRevenue(doc, report, y) {
  y = sectionTitle(doc, "Revenue", y);
  const rows = report.charts?.paymentMethods || [];
  return table(doc, y, ["Payment Method", "Orders", "Revenue"], rows.map((row) => [
    paymentLabel(row.payment_method),
    number(row.order_count),
    money(row.total)
  ]), { emptyText: "No revenue found for this date range." });
}

function addItemsSold(doc, report, y) {
  y = sectionTitle(doc, "Items Sold", y);
  const rows = report.products || [];
  const body = rows.map((product) => [product.product_name, product.brand, number(product.quantity_sold), money(product.revenue_generated)]);
  if (rows.length) body.push(["Totals", "", number(tableTotal(rows, "quantity_sold")), money(tableTotal(rows, "revenue_generated"))]);
  return table(doc, y, ["Apparel", "Brand", "Quantity Sold", "Revenue"], body, { emptyText: "No sold items found for this date range." });
}

function addLowStock(doc, report, y) {
  y = sectionTitle(doc, "Low Stock Report", y);
  return table(doc, y, ["ID", "Name", "Brand", "Category", "Size", "Stock", "Status"], (report.lowStockProducts || []).map((product) => [
    `#${product.id}`,
    product.name,
    product.brand || "Other Brands",
    product.category || "Apparel",
    product.size || "",
    number(product.stock),
    product.status || "Low Stock"
  ]), { emptyText: "No low stock apparel right now.", fontSize: 7.5 });
}

function addInventory(doc, report, y) {
  y = sectionTitle(doc, "Inventory", y);
  y = table(doc, y, ["Metric", "Value"], [
    ["Total Apparel Items", number(report.inventory?.product_count)],
    ["Total Stock", number(report.inventory?.total_stock)],
    ["Low Stock Apparel", number(report.inventory?.low_stock_count)],
    ["Out of Stock Apparel", number(report.inventory?.out_of_stock_count)]
  ]);
  y = sectionTitle(doc, "Inventory Items", y);
  return table(doc, y, ["ID", "Name", "Brand", "Category", "Size", "Stock", "Price", "Status"], (report.inventoryProducts || []).map((product) => [
    `#${product.id}`,
    product.name,
    product.brand || "Other Brands",
    product.category || "Apparel",
    product.size || "",
    number(product.stock),
    money(product.price),
    product.status || ""
  ]), { emptyText: "No inventory records available.", fontSize: 6.8 });
}

function addFeedback(doc, report, y) {
  y = sectionTitle(doc, "Customer Feedback", y);
  return table(doc, y, ["Date", "Customer", "Rating", "Category", "Apparel", "Comment"], (report.feedback || []).map((review) => [
    formatDate(review.created_at),
    review.customer_name,
    `${number(review.rating)} / 5`,
    review.category,
    review.apparel,
    review.comment
  ]), { emptyText: "No customer feedback found for this date range.", fontSize: 6.8 });
}

function addBestSelling(doc, report, y) {
  y = sectionTitle(doc, "Best Selling Products", y);
  return table(doc, y, ["Apparel", "Brand", "Units Sold", "Revenue"], (report.topSellingProducts || []).map((product) => [
    product.name,
    product.brand,
    number(product.sold),
    money(product.revenue)
  ]), { emptyText: "No best selling products found for this date range." });
}

function addApparelPerformance(doc, report, y) {
  y = sectionTitle(doc, "Apparel Performance", y);
  return table(doc, y, ["Apparel", "Brand", "Category", "Size", "Orders", "Qty Sold", "Revenue", "Avg Price"], (report.apparelPerformance || []).map((product) => [
    product.name,
    product.brand,
    product.category || "Apparel",
    product.size || "",
    number(product.orders_count),
    number(product.quantity_sold),
    money(product.revenue),
    money(product.average_price)
  ]), { emptyText: "No apparel performance found for this date range.", fontSize: 6.8 });
}

function addMonthlySales(doc, report, y) {
  y = sectionTitle(doc, "Monthly Sales", y);
  return table(doc, y, ["Month", "Orders", "Sales"], (report.monthlySales || []).map((row) => [
    row.month,
    number(row.orders_count),
    money(row.total)
  ]), { emptyText: "No monthly sales found for this date range." });
}

function addCharts(doc, chartImages, y) {
  const images = [chartImages?.sales, chartImages?.payment].filter(Boolean);
  if (!images.length) return y;
  y = sectionTitle(doc, "Charts", y);
  const { width } = pageMetrics(doc);
  images.forEach((image) => {
    y = ensureSpace(doc, y, 70);
    doc.addImage(image, "PNG", 14, y, width - 28, 62);
    y += 70;
  });
  return y;
}

export async function exportSalesReportPdf({ report, range, options = defaultReportOptions, chartRefs }) {
  const reportOptions = { ...defaultReportOptions, ...options, dateRange: options?.dateRange || range || defaultReportOptions.dateRange };
  const doc = new jsPDF(reportOptions.orientation === "landscape" ? "l" : "p", "mm", reportOptions.paperSize || "a4");
  addHeader(doc, report, reportOptions);
  let y = addReportMeta(doc, report, reportOptions);
  const chartImages = {
    sales: await captureElement(chartRefs?.sales?.current),
    payment: await captureElement(chartRefs?.payment?.current)
  };

  if (includesReport(reportOptions, "salesSummary")) y = addSalesSummary(doc, report, y);
  if (includesReport(reportOptions, "ordersSummary")) y = addOrdersSummary(doc, report, y);
  if (includesReport(reportOptions, "revenue")) y = addRevenue(doc, report, y);
  if (includesReport(reportOptions, "itemsSold")) y = addItemsSold(doc, report, y);
  if (includesReport(reportOptions, "lowStock")) y = addLowStock(doc, report, y);
  if (includesReport(reportOptions, "inventory")) y = addInventory(doc, report, y);
  if (includesReport(reportOptions, "customerFeedback")) y = addFeedback(doc, report, y);
  if (includesReport(reportOptions, "bestSellingProducts")) y = addBestSelling(doc, report, y);
  if (includesReport(reportOptions, "apparelPerformance")) y = addApparelPerformance(doc, report, y);
  if (includesReport(reportOptions, "monthlySales")) y = addMonthlySales(doc, report, y);
  if (includesReport(reportOptions, "salesSummary") || includesReport(reportOptions, "revenue") || includesReport(reportOptions, "monthlySales")) addCharts(doc, chartImages, y);

  addFooter(doc);
  doc.save(reportFilename(new Date(report.reportDate || Date.now())));
}
