CREATE TABLE IF NOT EXISTS system_settings (
  id TINYINT PRIMARY KEY,
  config_json LONGTEXT NOT NULL,
  openai_api_key_encrypted TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
